CREATE EXTENSION IF NOT EXISTS postgis ;
CREATE EXTENSION IF NOT EXISTS pgsfti ;
CREATE EXTENSION IF NOT EXISTS unaccent ;
CREATE EXTENSION IF NOT EXISTS pg_trgm ;
CREATE EXTENSION IF NOT EXISTS postal ;